spring.application.name=todo-task-manager
spring.datasource.url=jdbc:mysql://localhost:3306/capgemini_task_db
spring.datasource.username=root
spring.datasource.password=savi2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

